//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWebApp.LocalizationFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskTracker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskTracker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskWebApp.LocalizationFiles.TaskTracker", typeof(TaskTracker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have access to this page....
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task Assignees.
        /// </summary>
        public static string AddTaskAssignees {
            get {
                return ResourceManager.GetString("AddTaskAssignees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add several assignees hold down the Ctrl key (or &quot;Cmd&quot; for Mac).
        /// </summary>
        public static string AddTaskAssigneesToolTip {
            get {
                return ResourceManager.GetString("AddTaskAssigneesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        public static string AddTaskButtonText {
            get {
                return ResourceManager.GetString("AddTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddTaskDescription {
            get {
                return ResourceManager.GetString("AddTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string AddTaskFormTitle {
            get {
                return ResourceManager.GetString("AddTaskFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AddTaskName {
            get {
                return ResourceManager.GetString("AddTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string AddTaskPriority {
            get {
                return ResourceManager.GetString("AddTaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Section.
        /// </summary>
        public static string AdminSection {
            get {
                return ResourceManager.GetString("AdminSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee:.
        /// </summary>
        public static string CardAssignee {
            get {
                return ResourceManager.GetString("CardAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not assigned.
        /// </summary>
        public static string CardNotAssigned {
            get {
                return ResourceManager.GetString("CardNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        public static string CardOwner {
            get {
                return ResourceManager.GetString("CardOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A journey of a thousand miles begins with a single step.
        /// </summary>
        public static string GreetingCardDescription {
            get {
                return ResourceManager.GetString("GreetingCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there.
        /// </summary>
        public static string GreetingCardTitle {
            get {
                return ResourceManager.GetString("GreetingCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the main page.
        /// </summary>
        public static string MainPageLink {
            get {
                return ResourceManager.GetString("MainPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to procrastinate? Here are some random news for you.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        public static string UpdateTaskFormButtonText {
            get {
                return ResourceManager.GetString("UpdateTaskFormButtonText", resourceCulture);
            }
        }
    }
}
